when:
  - event: push
    branch: main

steps:
  - name: build
    image: docker.io/library/debian:bookworm-slim
    commands:
      - apt-get update && apt-get install wget -y
      - wget https://github.com/getzola/zola/releases/download/v0.19.2/zola-v0.19.2-x86_64-unknown-linux-gnu.tar.gz
      - tar -xvf zola-v0.19.2-x86_64-unknown-linux-gnu.tar.gz
      - ./zola build
      - rm -rf /tmp/output/*
      - cp -TR public /tmp/output
    volumes:
      - /srv/blog:/tmp/output