when:
  - event: push
    branch: main

steps:
  - name: build
    image: ghcr.io/getzola/zola:v0.18.0
    entrypoint: ["zola", "build", "--output-dir /tmp/output", "--force"]
    volumes:
      - /srv/blog:/tmp/output