## The URL the site will be built for
base_url = "https://xyquadrat.ch"

title = "xyquadrat.ch"
description = "Blog about software, ETH and life"

default_language = "en"

compile_sass = true
minify_html = true

## Generate RSS feed at `atom.xml`
generate_feeds = true
feed_limit = 20

[markdown]
## Whether to do syntax highlighting
## Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

external_links_target_blank = true

smart_punctuation = true
lazy_async_image = true
